# Generated by Django 4.2 on 2023-08-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Romm',
            new_name='Room',
        ),
    ]
